tasks:   
  - name: Python Requirements
    init: |
      pip3 install --upgrade pip
      pip3 install -r requirements.txt


vscode:
  extensions:
    - almenon.arepl
    - ms-python.python

image:
  file: .gitpod.dockerfile
